### PR TITLE
Fix ErrorWriter to be codec agnostic

### LINKED ISSUE #689: ErrorWriter.IsSupported is overly strict
Currently `ErrorWriter.IsSupported` uses the currently supported codecs (provided in the form of handler options) to compute all of the possible content-types that the server would support. However, this is not necessary. There are only four protocol types, and the actual registered codecs aren't necessary in order to classify them:
1. If the content-type is `application/grpc` or starts with `application/grpc+` then it's a gRPC request. 
2. If the content-type is `application/grpc-web` or starts with `application/grpc-web+` then it's a gRPC-Web request. 
3. If the content-type starts with `application/connect+` then it's a Connect streaming request. 
4. Lastly, if the content-type starts with `application/` and matches none of the above OR it has a `Connect-Protocol-Version: 1` header OR it uses a GET HTTP method and includes a `connect=v1` query param then it's a Connect unary request.
5. Only when none of the above apply should the request be un-classifiable and `IsSupported` return false.

In all of the above cases, the actual supported codecs are irrelevant because, once classified as above, an error can be correctly written (error formats are codec-agnostic).

Addressing this would also enable error handling that more closely resembles gRPC. In gRPC servers, if the content-type is not a gRPC content-type (i.e. it is not `application/grpc` and does not start with `application/grpc+`) then the server sends back a 415 HTTP status code, which clients will then classify as an unknown error. If it's a gRPC content-type, but not a supported codec, the server sends back a gRPC error (HTTP status code 200, error code and message in HTTP trailers) with a code of "internal". So with the above logic, when the content-type is not supported, an `ErrorWriter` could be used to write an RPC internal error and a 415 HTTP status code only used if the `ErrorWriter` reports that the request is unsupported.

### PR DESCRIPTION
**Pull request by emcfarlane**
This PR changes the ErrorWriter to be more lenient with classifying protocols. Errors codecs are agnostic to the codec used. Therefore we avoid checking the codec in classifying the request. IsSupported will return true for an unknown codec which allows the server to encode a better error message to the client. If not supported a 415 error response could be used to match gRPC server like handling. If not supported and trying to write an error the ErrorWriter will default to connects unary encoding (consistent with current behaviour).

Fixes #689

### CODE REVIEW

File: connect_ext_test.go [hunk 1]
```diff
@@ -2423,7 +2423,9 @@ func TestClientDisconnect(t *testing.T) {
 			assert.NotNil(t, err)
 			<-gotResponse
 			assert.NotNil(t, handlerReceiveErr)
-			assert.Equal(t, connect.CodeOf(handlerReceiveErr), connect.CodeCanceled)
+			if !assert.Equal(t, connect.CodeOf(handlerReceiveErr), connect.CodeCanceled) {
+				t.Logf("handlerReceiveErr: %v", handlerReceiveErr)
```
Comment (emcfarlane) [inline connect_ext_test.go:2427]: Unrelated, but noticed in testing. Raising the log to help debug better if seen in CI.

File: connect_ext_test.go [hunk 2]
```diff
@@ -2423,7 +2423,9 @@ func TestClientDisconnect(t *testing.T) {
...
+			}
```
Comment (akshayjshah) [inline connect_ext_test.go:2428]: `assert.Sprintf` is for this:

```suggestion
			assert.Equal(
				t,
				connect.CodeOf(handlerReceiveErr),
				connect.CodeCanceled,
				assert.Sprintf("handerReceiveErr: %v", handlerReceiveErr),
			)
```

At some point, we may want to migrate assertions to `testify` or just use `cmp` directly. I like `assert`-style utility libraries, but it's not worth the mental overhead of having a special approach just for this one repository.

File: error_writer.go [hunk 3]
```diff
@@ -54,69 +52,54 @@ type ErrorWriter struct {
 // Options supplied via [WithConditionalHandlerOptions] are ignored.
 func NewErrorWriter(opts ...HandlerOption) *ErrorWriter {
 	config := newHandlerConfig("", StreamTypeUnary, opts)
-	writer := &ErrorWriter{
+	codecs := newReadOnlyCodecs(config.Codecs)
```
Comment (akshayjshah) [inline error_writer.go:55]: The GoDoc for `NewErrorWriter` also needs to be updated to explain why we need `...HandlerOption`: now it's not for codecs, it's for the Connect version header.

File: error_writer.go [hunk 4]
```diff
@@ -54,69 +52,54 @@ type ErrorWriter struct {
...
 		}
+		return connectUnaryProtocol
+	case ctype == "":
+		if method != http.MethodGet {
+			break
+		}
+		if err := connectCheckProtocolVersion(request, w.requireConnectProtocolHeader); err != nil {
+			break
+		}
+		return connectUnaryProtocol
```
Comment (akshayjshah) [inline error_writer.go:102]: I'm finding the big switch with nested `break`s difficult to read. It'd be clearer to me if we had an `isPost := method == http.MethodPost` before the switch and inlined the HTTP verb checks into the case statements where possible.

File: error_writer.go [hunk 5]
```diff
@@ -54,69 +52,54 @@ type ErrorWriter struct {
...
+	case strings.HasPrefix(ctype, connectStreamingContentTypePrefix):
+		if method != http.MethodPost {
+			break
 		}
-		return connectUnaryProtocol
-	}
-	if _, ok := w.streamingConnectContentTypes[ctype]; ok {
 		if err := connectCheckProtocolVersion(request, w.requireConnectProtocolHeader); err != nil {
-			return unknownProtocol
+			break
```
Comment (akshayjshah) [inline error_writer.go:84]: Just want to flag that there's an open discussion about this in #700. Let's make sure we sync this up with whatever's decided in that thread before merging to `main`.

File: error_writer.go [hunk 6]
```diff
@@ -41,86 +41,58 @@ const (
...
-			return connectUnaryProtocol
+	case isPost && strings.HasPrefix(ctype, connectUnaryContentTypePrefix):
+		if err := connectCheckProtocolVersion(request, w.requireConnectProtocolHeader); err != nil {
+			return unknownProtocol
 		}
-		connectVersion = request.URL.Query().Get(connectUnaryConnectQueryParameter)
-		if connectVersion == connectUnaryConnectQueryValue {
-			return connectUnaryProtocol
+		return connectUnaryProtocol
+	case isGet && ctype == "":
```
Comment (jhump) [inline error_writer.go:88]: In order to be compatible with versions of connect-go prior to v1.13 ([which includes a fix for the content-type with GET requests](https://github.com/connectrpc/connect-go/pull/644/files#diff-cdd39981f92fb3d0b9c81ce742c64f5574d2aed55233f5fdd21a4a7ee80677f3R1049)), perhaps we should be more lenient here and either disregard the content-type or allow it to have a `connectUnaryContentTypePrefix` prefix.

Comment (emcfarlane) [reply error_writer.go]: Makes sense, dropped the check.

File: error_writer.go [hunk 7]
```diff
@@ -80,12 +80,12 @@ func (w *ErrorWriter) classifyRequest(request *http.Request) protocolType {
 			return unknownProtocol
 		}
 		return connectStreamProtocol
-	case isPost && strings.HasPrefix(ctype, connectUnaryContentTypePrefix):
+	case isPost && strings.HasPrefix(ctype, connectUnaryContentTypePrefix) && !strings.HasPrefix(ctype, grpcContentTypeDefault):
```
Comment (emcfarlane) [inline error_writer.go:83]: Should we retain the codec supported is a connect codec here? Even though it is error agnostic it is odd that a request can be classified as a connect request only on the `application/` prefix.

Comment (jhump) [reply error_writer.go:83]: Sorry, I don't understand the question.

> odd that a request can be classified as a connect request only on the application/ prefix

This wasn't the case before. To what exactly are you alluding? Do you mean the fact that we'll conflate _any_ `application/` prefix to mean a Connect unary content type? Or are you referring to the check you added to omit the gRPC content-types?

Comment (emcfarlane) [reply error_writer.go:83]: Should we remove the config settings for handling grpc and grpc web?

**Review by jhump — APPROVED** [review]
